hook update to check email via function

diff --git a/pre-commit-email-hook b/pre-commit-email-hook
--- a/pre-commit-email-hook
+++ b/pre-commit-email-hook
@@ -1,23 +1,26 @@
 #!/bin/sh
 
-EMAIL=$(git config user.email)
-EMAIL_LEN=${#EMAIL}
+function checkEmail() {
 
-EXPECTED_EMAIL_DOMAIN="@users.noreply.github.com"
-EXPECTED_EMAIL_DOMAIN_LEN=${#EXPECTED_EMAIL_DOMAIN}
+  EMAIL=$(git config user.email)
+  EMAIL_LEN=${#EMAIL}
 
-if [[ ${EMAIL} != *"${EXPECTED_EMAIL_DOMAIN}" ]]
-then
-  echo 'email expected domain of '${EXPECTED_EMAIL_DOMAIN};
-  echo '';
-  exit 1;
-fi
+  EXPECTED_EMAIL_DOMAIN="@users.noreply.github.com"
+  EXPECTED_EMAIL_DOMAIN_LEN=${#EXPECTED_EMAIL_DOMAIN}
 
+  if [[ ${EMAIL} != *"${EXPECTED_EMAIL_DOMAIN}" ]]
+  then
+    echo 'email expected domain of '${EXPECTED_EMAIL_DOMAIN};
+    echo '';
+    exit 1;
+  fi
 
-if [[ "${EMAIL_LEN}" -le "${EXPECTED_EMAIL_DOMAIN_LEN}" ]]
-then
-  echo 'email missing username for '${EXPECTED_EMAIL_DOMAIN};
-  echo '';
-  exit 1;
-fi
+  if [[ "${EMAIL_LEN}" -le "${EXPECTED_EMAIL_DOMAIN_LEN}" ]]
+  then
+    echo 'email missing username for '${EXPECTED_EMAIL_DOMAIN};
+    echo '';
+    exit 1;
+  fi
+}
 
+checkEmail
